import type { DetectionResult } from "@/types";
import { formatDate } from "./utils";

/**
 * Generates a plain-text summary of a detection result and triggers a
 * client-side download — no server round-trip or PDF dependency needed.
 */
export function downloadReport(result: DetectionResult) {
  const lines = [
    "DeepShield AI — Deepfake Detection Report",
    "=".repeat(44),
    "",
    `File:                 ${result.filename}`,
    `Verdict:              ${result.prediction}`,
    `Confidence:           ${result.confidence.toFixed(1)}%`,
    `Risk Level:           ${result.riskLevel}`,
    `Average Frame Score:  ${result.avgFrameScore.toFixed(1)}%`,
    `Frames Analyzed:      ${result.framesProcessed}`,
    `Processing Time:      ${result.processingTime.toFixed(2)}s`,
    `Model Used:           ${result.modelUsed}`,
    `Detection Timestamp:  ${formatDate(result.createdAt)}`,
    "",
    "Analysis Summary",
    "-".repeat(44),
    result.explanation,
    "",
    "-".repeat(44),
    "Generated by DeepShield AI. This report reflects an automated AI",
    "assessment and should be reviewed alongside other evidence before",
    "being used for high-stakes decisions.",
  ];

  const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `deepshield-report-${result.id}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
